version: '3'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    stdin_open: true  # Need this line to avoid an error on startup
    volumes:
      - './frontend/src:/srv/src'
    ports:
      - '3000:3000'
